### ISSUE TITLE
Handle pagination without knowing number of pages or last page

### ISSUE THREAD

**Issue by flikkr** [hafees/riverpod_infinite_scroll#2]
Hi there, thanks for the package. I am using Supabase in my project and there is no build-in way to handle pagination, I need to fetch pages based on the current page number and the size of each page, something like this:
```dart
@override
  Future<List<Foo>> getAll([PaginateOptions? options]) async {
    final range = pageRange(options);
    final res = await supabase
        .from(tableName)
        .select()
        .eq('created_by', userId)
        .range(range.start, range.end)
        .order('created_at', ascending: false);
    final foos = res.map((foo) => Foo.fromJson(foo)).toList();
    return foos;
  }
```

Based on the docs, it seems I need to also provide the last page and the total number of pages in the `Pagination` object, but I don't have access to that data unless I make another query for that. Is there a way to handle pagination without providing that data? Maybe can expose a parameter in `PaginatedListView` to notify if the list has reached the last page?
```dart
Future<PaginatedResponse<TmdbMovie>> searchMovies({
    int page = 1,
    String? query = '',
  }) async {
    await Future<void>.delayed(const Duration(seconds: 2));
    final results = await dio.get<Map<String, dynamic>>(
      'search/movie?query=$query&include_adult=false&page=$page',
    );

    return PaginatedResponse.fromJson(
      results.data!,
      dataMapper: TmdbMovie.fromJson,
      dataField: 'results',
      paginationParser: (data) => Pagination(
        totalNumber: data['total_results'] as int,
        currentPage: data['page'] as int,
        lastPage: data['total_pages'] as int,
      ),
    );
  }
```

**Comment by hafees** [comment]
@flikkr  The pagination will work as long as the `currentPage` is less than `lastPage`. Total number of records `totalNumber` (it is the count of total records, not pages) is not used for any pagination logic  (Useful if you want to show a custom loader with pagination info showing the total number of records). So it should work if you provide `lastPage` as `currentPage + 1` or so. When you reach the end just make both the same.

**Comment by flikkr** [comment]
@hafees Got it, thanks. I figured out I can also get the total count as well as the data from my query by using the `.count()` function.
